[package]
name = "proto"
version = "1.0.0"
edition = "2021"

[lib]
name = "proto"
path = "lib.rs"

[dependencies]
prost = "0.12.1"
prost-types = "0.12.1"
serde = "1.0.192"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic = "0.10.2"

[build-dependencies]
tonic-build = { version = "0.10.2", features = ["prost"] }
