[package]
name = "authorization-service"
version = "1.0.0"
edition = "2021"


[dependencies]
oauth2 = "4.4.2"
prost-types = "0.12.1"
proto = { path = "../../packages/proto" }
serde_json = "1.0.108"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic = "0.10.2"
