name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Install Go
        uses: actions/setup-go@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm dlx nx run-many -t lint

  check:
    name: Check
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Install Go
        uses: actions/setup-go@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run Check
        run: pnpm dlx nx run-many -t check

  test:
    name: Unit Tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Install Go
        uses: actions/setup-go@v4

        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm dlx nx run-many -t test
