name: Continuous Integration
on:
  push:
    paths:
      - "**.{cjs, js, jsx, ts, tsx, proto}"
    branches:
      - main
  pull_request:
    paths:
      - "**.{cjs, js, jsx, ts, tsx, proto}"
    branches:
      - main
jobs:
  lint:
    name: Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

  check:
    name: Check
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Check
        run: pnpm check

  test:
    name: Unit Tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm test
